[
  {
    Title: "Guardians of the Galaxy Vol. 2",
    Year: "2017",
    Rated: "PG-13",
    Released: "05 May 2017",
    Runtime: "136 min",
    Genre: "Action, Adventure, Comedy",
    Director: "James Gunn",
    Writer: "James Gunn, Dan Abnett, Andy Lanning",
    Actors: "Chris Pratt, Zoe Saldana, Dave Bautista",
    Plot: "The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord's encounter with his father, the ambitious celestial being Ego.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 15 wins & 60 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "85%",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
    Metascore: "67",
    imdbRating: "7.6",
    imdbVotes: "772,214",
    imdbID: "tt3896198",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$389,813,101",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "87%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,592,712",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$292,587,330",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Game of Thrones",
    Year: "2011–2019",
    Rated: "TV-MA",
    Released: "17 Apr 2011",
    Runtime: "57 min",
    Genre: "Action, Adventure, Drama",
    Director: "N/A",
    Writer: "David Benioff, D.B. Weiss",
    Actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
    Plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 59 Primetime Emmys. 397 wins & 655 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGY3NTg1ODMtOGIzZS00YWFiLTgzYzktNzBiYWZkYjcwNGRhXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.2",
    imdbVotes: "2,348,679",
    imdbID: "tt0944947",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "Stranger Things",
    Year: "2016–2025",
    Rated: "TV-14",
    Released: "15 Jul 2016",
    Runtime: "51 min",
    Genre: "Drama, Fantasy, Horror",
    Director: "N/A",
    Writer: "Matt Duffer, Ross Duffer",
    Actors: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
    Plot: "In 1980s Indiana, a group of young friends witness supernatural forces and secret government exploits. As they search for answers, the children unravel a series of extraordinary mysteries.",
    Language: "English",
    Country: "United States",
    Awards: "Won 12 Primetime Emmys. 113 wins & 323 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE2N2MyMzEtNmU5NS00OTI0LTlkNTMtMWM1YWYyNmU4NmY0XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "1,380,012",
    imdbID: "tt4574334",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "The Matrix",
    Year: "1999",
    Rated: "R",
    Released: "31 Mar 1999",
    Runtime: "136 min",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Writer: "Lilly Wachowski, Lana Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    Plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    Language: "English",
    Country: "United States, Australia",
    Awards: "Won 4 Oscars. 42 wins & 52 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "83%",
      },
      {
        Source: "Metacritic",
        Value: "73/100",
      },
    ],
    Metascore: "73",
    imdbRating: "8.7",
    imdbVotes: "2,087,394",
    imdbID: "tt0133093",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$172,076,928",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
